name:                aoc2016
version:             0.1.0.0
github:              "Welperooni/aoc2016"
license:             BSD3
author:              "Welperooni"
maintainer:          "welperooni@gmail.com"
copyright:           "Welperooni"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Welperooni/aoc2016#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - split
  - lens
  - transformers
  - containers
  - raw-strings-qq
  - MissingH
  - dlist
  default-extensions: 
  - ViewPatterns
  - LambdaCase
  - GeneralizedNewtypeDeriving
  - TemplateHaskell
  - QuasiQuotes
  - RecordWildCards
  - GADTs
  - DataKinds
  - ScopedTypeVariables
  - TypeApplications
  - KindSignatures
  - FlexibleInstances
  - TypeFamilies
  - TypeOperators
  - RankNTypes
  - AllowAmbiguousTypes
  - UndecidableInstances
  - PartialTypeSignatures
  - FlexibleContexts
  - ConstrainedClassMethods

executables:
  aoc2016-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2016
